# Generated by Django 5.0 on 2023-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height_image', upload_to='images/%Y/%M/%d', width_field='width_image')),
                ('width_image', models.IntegerField(default=0)),
                ('height_image', models.IntegerField(default=0)),
                ('altetrantive', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('image_hash', models.CharField(blank=True, max_length=40, null=True, verbose_name='hash image')),
                ('image_size', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
