# Generated by Django 5.0 on 2023-12-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='hash_image',
            new_name='image_hash',
        ),
        migrations.AddField(
            model_name='image',
            name='image_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
