# Generated by Django 5.0 on 2023-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_description_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fa_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='persion name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
