# Generated by Django 5.0 on 2023-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(max_length=150, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fa_name',
            field=models.CharField(max_length=150, verbose_name='persion name'),
        ),
    ]
