# Generated by Django 5.0 on 2023-12-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_public_alter_product_en_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
